image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1244.87565,    0.     ,  289.20494,
            0.     , 1255.17164,  270.46296,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.963593, 5.656296, -0.017697, 0.043367, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1213.12573,    0.     ,  303.03873,    0.     ,
            0.     , 1241.41589,  265.2451 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]