twist_mux:
  ros__parameters:
    use_stamped: false   # Forces the node to subscribe and publish standard Twist messages
    topics:
      navigation:
        topic: cmd_vel_smoothed
        timeout: 0.5
        priority: 10
      joystick:
        topic: cmd_vel_joy
        timeout: 0.1
        priority: 100 # Higher priority overrides navigation