waypoints_GPS:

- name      : WP_1
  latitude  : 36.3058610
  longitude : 120.4968798
  yaw       : -56.64
  wait_time : 0.0

- name      : WP_2
  latitude  : 36.3058564
  longitude : 120.4968834
  yaw       : -56.04
  wait_time : 0.0

- name      : WP_3
  latitude  : 36.3058432
  longitude : 120.4968968
  yaw       : -57.92
  wait_time : 0.0

- name      : WP_4
  latitude  : 36.3058254
  longitude : 120.4969065
  yaw       : -76.73
  wait_time : 0.0

- name      : WP_5
  latitude  : 36.3058045
  longitude : 120.4969103
  yaw       : -113.02
  wait_time : 0.0

- name      : WP_6
  latitude  : 36.3057871
  longitude : 120.4968957
  yaw       : -177.84
  wait_time : 0.0

- name      : WP_7
  latitude  : 36.3057912
  longitude : 120.4968705
  yaw       : 128.69
  wait_time : 0.0

- name      : WP_8
  latitude  : 36.3058083
  longitude : 120.4968586
  yaw       : 100.56
  wait_time : 0.0

- name      : WP_9
  latitude  : 36.3058270
  longitude : 120.4968548
  yaw       : 93.56
  wait_time : 0.0

- name      : WP_10
  latitude  : 36.3058452
  longitude : 120.4968533
  yaw       : 103.10
  wait_time : 0.0

- name      : WP_11
  latitude  : 36.3058639
  longitude : 120.4968472
  yaw       : 107.46
  wait_time : 0.0

- name      : WP_12
  latitude  : 36.3058829
  longitude : 120.4968399
  yaw       : 62.13
  wait_time : 0.0

- name      : WP_13
  latitude  : 36.3058977
  longitude : 120.4968538
  yaw       : -15.29
  wait_time : 0.0

- name      : WP_14
  latitude  : 36.3058868
  longitude : 120.4968704
  yaw       : -63.13
  wait_time : 0.0

- name      : WP_15
  latitude  : 36.3058730
  longitude : 120.4968785
  yaw       : -76.32
  wait_time : 0.0

