waypoints_GPS:

- name      : WP_1
  latitude  : 36.3058703
  longitude : 120.4968211
  yaw       : 0.00
  wait_time : 0.0

- name      : WP_2
  latitude  : 36.3058702
  longitude : 120.4968211
  yaw       : 0.00
  wait_time : 0.0

- name      : WP_3
  latitude  : 36.3058702
  longitude : 120.4968211
  yaw       : 0.00
  wait_time : 0.0

- name      : WP_4
  latitude  : 36.3058702
  longitude : 120.4968211
  yaw       : 0.00
  wait_time : 0.0

- name      : WP_5
  latitude  : 36.3058702
  longitude : 120.4968211
  yaw       : 0.00
  wait_time : 0.0

- name      : WP_6
  latitude  : 36.3058702
  longitude : 120.4968212
  yaw       : 0.00
  wait_time : 0.0

- name      : WP_7
  latitude  : 36.3058702
  longitude : 120.4968212
  yaw       : 0.00
  wait_time : 0.0

- name      : WP_8
  latitude  : 36.3058702
  longitude : 120.4968212
  yaw       : 0.00
  wait_time : 0.0

- name      : WP_9
  latitude  : 36.3058702
  longitude : 120.4968212
  yaw       : 0.00
  wait_time : 0.0

- name      : WP_10
  latitude  : 36.3058702
  longitude : 120.4968212
  yaw       : 0.00
  wait_time : 0.0

